metalsoft-update-k8s-ips workaround for metallb cidr being a NodeIP

diff --git a/env-scripts/metalsoft-update-k8s-ips b/env-scripts/metalsoft-update-k8s-ips
--- a/env-scripts/metalsoft-update-k8s-ips
+++ b/env-scripts/metalsoft-update-k8s-ips
@@ -145,7 +145,7 @@ EOFF
 
 #sed -i "s/\(\s\+-\) 10\.0\..*\/32/\1 ${cip}\/32/g" /tmp/IPAddressPool.yaml
 echo "[i] Waiting for Metallb pods to start, then the new configuration will be applied"
-kubectl -n metallb-system apply -f /tmp/IPAddressPool.yaml
+kubectl -n metallb-system apply -f /tmp/IPAddressPool.yaml || { echo -e "${yellow}Error: Unable to apply IPAddressPool, trying workaround...${nc}"; kubectl -n metallb-system get validatingwebhookconfiguration --no-headers|awk '{print $1}'|while read v hook age;do kubectl -n metallb-system delete validatingwebhookconfiguration $v;done && kubectl -n metallb-system apply -f /tmp/IPAddressPool.yaml; }
 ec=$?
 kubectl -n demo-metalsoft exec -it deploy/mysql -- mysql -A bsi_powerdns -e "UPDATE records SET content = '$cip' where domain_id=1 and type='A' and name='ip.demo.metalsoft.io'"
 if [ "$last_aip" != "$aip" ];then
