metalsoft-update-k8s-ips Navigate to link update

diff --git a/env-scripts/metalsoft-update-k8s-ips b/env-scripts/metalsoft-update-k8s-ips
--- a/env-scripts/metalsoft-update-k8s-ips
+++ b/env-scripts/metalsoft-update-k8s-ips
@@ -188,13 +188,12 @@ fi
 
 # add IP with hostname to /etc/hosts
 hn="$(hostname -f 2>/dev/null)" ||  hn="$(cat /etc/hostname)"
-test -f /etc/.ms_hostname && main_domain="$(cat /etc/.ms_hostname 2>/dev/null)"
+test -f /etc/metalsoft && main_domain="$(grep MS_HOSTNAME /etc/metalsoft 2>/dev/null|cut -d '=' -f2)"
 test -z "$main_domain" && main_domain="$(grep cookie_domain ${MS_MANIFESTS_FOLDER}/configmaps.yaml 2>/dev/null|head -1|cut -d '"' -f2|sed 's/^\.//g')"
 test -z "$main_domain" && main_domain="$(grep 'match: Host' ${MS_MANIFESTS_FOLDER}/ingressroutes.yaml 2>/dev/null|grep -Ev 'repo\.|registry\.'|cut -d '`' -f2|head -1)"
 test -n "$hn" && sed -i "/\b${hn}\b/d" /etc/hosts && echo "$cip $hn cluster.demo.metalsoft.io controller-demo.metalsoft.io repo.${main_domain} repo-internal.${main_domain} $main_domain" >> /etc/hosts
-test -n "$main_domain" && echo "$main_domain" > /etc/.ms_hostname 2>/dev/null
-grep -q " \b$main_domain\b" /etc/hosts || echo "$cip $main_domain" >> /etc/hosts 2>/dev/null
 
+#grep -q " \b$main_domain\b" /etc/hosts || echo "$cip $main_domain" >> /etc/hosts 2>/dev/null
 if ! grep -q "^MS_HOSTNAME=" /etc/metalsoft; then
     echo "MS_HOSTNAME=$main_domain" >> /etc/metalsoft
 else
@@ -446,7 +445,7 @@ if [ -f "${MS_MANIFESTS_FOLDER}/sc-ms-agent-deployment.yaml" ];then
     fi
 fi
 
-test ${ec} -eq 0 && echo -e "\n[\e[1;32m✓\e[0m] ${lightgreen}Navigate to: https://${main_domain}/${nc} \nIf you get connection reset errors, you can rerun the script with same parameters:\n${me} $@\n" || echo -e "\n[\e[1;31m✗\e[0m][${ec}]${lightred}Some errors were seen. Please rerun this script again, once all pods have started:\n${me} $@ ${nc}\n"
+test ${ec} -eq 0 && echo -e "\n[\e[1;32m✓\e[0m] ${lightgreen}Navigate to: https://${hn}/${nc} \nIf you get connection reset errors, you can rerun the script with same parameters:\n${me} $@\n" || echo -e "\n[\e[1;31m✗\e[0m][${ec}]${lightred}Some errors were seen. Please rerun this script again, once all pods have started:\n${me} $@ ${nc}\n"
 
 echo
 echo "[i] Helm releases:"
