improve metalsoft-update-k8s-ips ip validation

diff --git a/env-scripts/metalsoft-update-k8s-ips b/env-scripts/metalsoft-update-k8s-ips
--- a/env-scripts/metalsoft-update-k8s-ips
+++ b/env-scripts/metalsoft-update-k8s-ips
@@ -45,9 +45,8 @@ fi
 #                 exit 2
 #         fi
 # fi
-
-cip=$1
-aip=$2
+if [[ $1 =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$  ]]; then cip="$1"; else echo "[i] Error: Invalid k8s IP: $1"; exit 1;fi
+if [[ $2 =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$  ]]; then aip="$2"; else echo "[i] Error: Invalid agents IP: $2"; exit 1;fi
 echo "[i] k8s IP: $cip"
 echo "[i] agents IP: $aip"
 
