netplan-cli discovers gw based on ip/mask

diff --git a/env-scripts/netplan-cli b/env-scripts/netplan-cli
--- a/env-scripts/netplan-cli
+++ b/env-scripts/netplan-cli
@@ -54,10 +54,22 @@ function set_dhcp()
 	exit 0
 }
 
+function calculate_gw()
+{
+_gwip="$1"
+IP=${_gwip%%/*}
+PREFIX=${_gwip##*/}
+IFS=. read -r i1 i2 i3 i4 <<< $IP
+IFS=. read -r xx m1 m2 m3 m4 <<< $(for a in $(seq 1 32); do if [ $(((a - 1) % 8)) -eq 0 ]; then echo -n .; fi; if [ $a -le $PREFIX ]; then echo -n 1; else echo -n 0; fi; done)
+gw="$(printf "%d.%d.%d.%d\n" "$((i1 & (2#$m1)))" "$((i2 & (2#$m2)))" "$((i3 & (2#$m3)))" "$(((i4 & (2#$m4)) + 1))")"
+}
+
 function set_static()
 {
-	if [ -n "$setnic" ] && [ -n "$ip" ] && [[ $ip =~ "/" ]] && [ -n "$gw" ] && [ -n "$nameservers" ];then
-		echo [i] Setting Interface: ${lightgreen}$setnic${nc} to: IP/Mask: ${lightgreen}$ip${nc}, GW: ${lightgreen}$gw${nc}, Nameservers: ${lightgreen}$nameservers${nc}
+	if [ -n "$setnic" ] && [ -n "$ip" ] && [[ $ip =~ "/" ]] && [ -n "$nameservers" ];then
+		test -z "$gw" && calculate_gw $ip && echo "[i] ${bold}Gateway was found to be: ${nc}${lightred}$gw${nc} ${bold}If this is incorect use the -g parameter to set Gateway${nc}"
+		test -z "$gw" && echo -e "[\e[1;31m✗\e[0m] ${lightred} Error: Cannot set static IP as Gateway is not specified. Please set -g parameter${nc}" && exit 4
+		echo "[i] Setting Interface: ${lightgreen}$setnic${nc} to: IP/Mask: ${lightgreen}$ip${nc}, GW: ${lightgreen}$gw${nc}, Nameservers: ${lightgreen}$nameservers${nc}"
 		netplan set ethernets.${setnic}.dhcp4=no
 		netplan set ethernets.${setnic}.routes=null
 		netplan set ethernets.${setnic}.routes="[{\"to\": \"default\",\"via\":\"${gw}\"}]"
